# Generated by Django 4.2.5 on 2024-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo_e_imagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subirdumentoimagen',
            name='documento',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='subirdumentoimagen',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
